; CCtrl firmware project configuration
[platformio]
default_envs = master_esp32s3, encoder_node_atmega328p, encoder_node_ch32v006

[env]
framework = arduino
monitor_speed = 2000000

[env:encoder_node_atmega328p]
platform = atmelavr
board = pro8MHzatmega328
board_build.f_cpu = 8000000L
upload_protocol = usbasp
upload_flags =
    -Pusb
    -B4
    -e
lib_deps =
    robtillaart/AS5600 @ ^0.6.4
build_src_filter =
    -<*>
    +<node_avr/>
    +<shared/>

[env:encoder_node_ch32v006]
platform = ch32v
board = genericCH32V006F8P6
framework = noneos-sdk
upload_protocol = wch-link
monitor_speed = 250000
board_build.clock_source = hse+pll
board_build.f_cpu = 48000000L
build_flags =
    -Isrc/shared
build_src_filter =
    -<*>
    +<node_ch32v006/>
    +<shared/>

[env:master_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.f_cpu = 80000000L
upload_protocol = esptool
build_unflags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
    -Iinclude
    -Ilib
    -Isrc
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    frankboesing/FastCRC @ ^1.41
    olikraus/U8g2 @ ^2.36.4
build_src_filter =
    -<*>
    +<master/>
    +<shared/>
    +<ui_runtime/>
